### PR TITLE
Get up to date with newest PLEXIL

### PR DESCRIPTION
**Pull request by kmdalal**
This change brings OW PLEXIL code and its underlying C++ support up to date with the newest PLEXIL.  It required many small code changes, but should have no effect on behavior.  There was some minor refactoring done in the process.

The version of PLEXIL used has been tagged, and this tag is documented in the OW setup guide, which is on the same hotfix branch of ow_simulator.  See this in https://github.com/nasa/ow_simulator/pull/38

To test this change, you must first bring your PLEXIL installation up to date:

```
cd $PLEXIL_HOME
git checkout releases/plexil-4
git pull
make squeaky-clean
make
```
Next, rebuild ow_autonomy:
```
cd <ow_workspace>/build
rm -rf ow_autonomy
cd <ow_workspace>/src
catkin build ow_autonomy
```

ow_autonomy should build without errors or warnings.  Next, start a simulation (any) and run a plan of your choice (one should be a sufficient test).   E.g. you can run the default demo plan with:
```
roslaunch ow_autonomy autonomy_node.launch
```

### CODE REVIEW

**Comment by lanseafood** [comment]
@kmdalal 

I went to the ow_autonomy and checked out your branch, then followed the rest of your instructions. Not sure if I needed to switch all my other repos to the melodic-devel too?

 plexil build is fine and so is the autonomy build, but when going to run the autonomy node, I'm getting this hang and no ROS windows are popping up

image

**Review by lanseafood — COMMENTED** [review]
I went to the ow_autonomy and checked out your branch, then followed the rest of your instructions. Not sure if I needed to switch all my other repos to the melodic-devel too?

plexil build is fine and so is the autonomy build, but when going to run the autonomy node, I'm getting this hang and no ROS windows are popping up

image

**Comment by kmdalal** [comment]
Lanssie, have you not started the simulator first?   E.g.  
`roslaunch ow europa_terminator_workspace.launch`
The autonomy node does not open any windows.

**Review by mogumbo — APPROVED** [review]

**Comment by lanseafood** [comment]
> Lanssie, have you started the simulator first? E.g.
> `roslaunch ow europa_terminator_workspace.launch`
> The autonomy node does not open any windows. However, the simulator must be started first, because autonomy immediately starts running a plan. I'd like to change this someday (there's a Jira for it).
> Also, not important that other repos be on melodic-devel for this test.

Hey Mike, 

I tried running the simulator and notice these errors, seems like because of the time, nothing but rqt will open..

image

**Comment by lanseafood** [comment]
> > Lanssie, have you started the simulator first? E.g.
> > `roslaunch ow europa_terminator_workspace.launch`
> > The autonomy node does not open any windows. However, the simulator must be started first, because autonomy immediately starts running a plan. I'd like to change this someday (there's a Jira for it).
> > Also, not important that other repos be on melodic-devel for this test.
> 
> Hey Mike,
> 
> I tried running the simulator and notice these errors, seems like because of the time, nothing but rqt will open..
> 
> image

Update, turns out my machine needed to be restarted... but it works! Yay 👍🏻

**Review by lanseafood — APPROVED** [review]
🎉

**Pull request merged**
