### PR TITLE
OCEANWATER-1238 Expanded Lookup interface to faults

### PR DESCRIPTION
**Pull request by kmdalal**
## Summary
- Introduces the notion of _general_ and _specific_ faults.  Please see the attached user guide chapters for background.  Specifically, read the new/edited sections "Execution and Goal Errors", "Fault Categories", and "Fault Flags" in the Fault document, and "General and Specific Faults" in Autonomy.  These documents are also found on the `release13-fault-modeling` branch of ow_simulator.wiki`.
- Some of the concepts above are briefly explained in `LanderInterface.h`.  Note that general fault Lookup names end with `Fault`, and specific ones end with `Error`.
- Fleshes out Lookup support for all fault flags defined in the testbeds (OceanWATERS, OWLAT, common).  Some code refactoring was needed to do this cleanly.
- Adds testbed-specific fault Lookup test plans.  Some plan refactoring was needed to do this cleanly.
- Renames `AntennaPanFault` and '`AntennaTiltFault` to `Antenna*Error` everywhere, to follow naming convention for specific faults.
- Unrelated: Removed unused and redundant OwInterface::getEndEffectorFT()

## Test

These instructions are very brief for now.

### OWLAT Test
- Build ow_plexil for OWLAT
- Start OWLAT (3 separate processes)
- Start the OWLAT Exec 
- Execute the plan `TestOwlatFaults`
- Since there is no way to inject faults, you'll just see "Polling for faults..." repeating.
- Ctrl-C in each window to quit.

### OceanWATERS Test
- Build ow_plexil for OceanWATERS
- Start any sim world
- Start the OW Exec
- Execute the plan `TestOwFaults`
- Using the Faults menu in RQT, inject various combinations of faults and observe results.
- When satisfied, Ctrl-C in each window to quit.

## Caveat

During this work, it was realized that the injectable force-torque sensor faults (zero value, signal bias) are not detectable by the `OwFaultDetection` node.  Hence, their associated Lookups always returns false because nothing sets the relevant fault flag.  Adding detection of F/T faults would be a separate work.

## Attachments

[Fault-Injection-and-Modeling.pdf](https://github.com/nasa/ow_autonomy/files/14910884/Fault-Injection-and-Modeling.pdf)

[Autonomy.pdf](https://github.com/nasa/ow_autonomy/files/14910883/Autonomy.pdf)

### CODE REVIEW

**Comment by kmdalal** [comment]
Comments inserted...

> When I inject `camera_left_trigger_failure` and capture an image, it results in a Camera execution error, but not a Camera goal error. Shouldn't it also be a goal error?

I think so, since the image is the goal.  I suspect the FaultDetection node does not set this flag.  Out of scope here, so I'll create a Jira for this.

> When I inject a `ant_pan_joint_locked_failure` the plan announces the pan error, but does not announce the presence of a PanTitlExecutionError. 

This seems like another bug (or missing feature) in FaultDetection.

Stranger still, when I then command `rosrun ow_lander pan.py 1.2` I see the following

> [transcript omitted]
> So ow_plexil acknowledges the presence of a PanTiltGoalError, but the plan does not. After unticking `ant_pan_joint_locked_failure` the plan continues to acknowledge the presence of a system fault. This makes sense, because the PanTiltGoalError has yet to be resolved, but shouldn't the plan be announcing that PanTiltGoalError?

I'll investigate this one.

> Aside from those I tried causing as many faults as I could think of and the rest seemed to work. As you know not all of our defined faults are reachable.

That's right, but I'm not sure which all are reachable.  I'll investigate and document, and also send the OWLAT team some questions.

**Comment by kmdalal** [comment]
@AstroStucky I have fixed both the problems you reported -- they were easy.  Update this branch, and also get the same branch of `ow_simulator`, which has its own PR.

**Comment by AstroStucky** [comment]
Sibling PR that I'll retest this against https://github.com/nasa/ow_simulator/pull/386

**Review by AstroStucky — APPROVED** [review]
Looks to work. Tested against the ow_simulator branch of the same name.

My only concern is when I inject a camera fault and capture an image, I still do not see the no image fault, but I do see the camera goal error
```
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] PLEXIL: System fault present.
[ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
```

**Comment by kmdalal** [comment]
> Looks to work. Tested against the ow_simulator branch of the same name.
> 
> My only concern is when I inject a camera fault and capture an image, I still do not see the no image fault, but I do see the camera goal error
> 
> ```
> [ INFO:/ow_exec_node] PLEXIL: Polling for faults...
> [ WARN:/ow_exec_node] PLEXIL: System fault present.
> [ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
> [ INFO:/ow_exec_node] PLEXIL: Polling for faults...
> ```

That is very odd.  I get the correct result every time, which includes other faults you should see:
```
[ INFO]: PLEXIL: Polling for faults...
[ WARN]: PLEXIL: System fault present.
[ WARN]: PLEXIL: Camera fault present.
[ WARN]: PLEXIL: Camera goal error present.
[ WARN]: PLEXIL: Camera execution error present.
[ WARN]: PLEXIL: No-Image error present.
```

Could you perhaps try again in a clean-built workspace?

**Comment by AstroStucky** [comment]
Same result. How are you triggering the camera? I'm using `rosrun ow_lander camera_capture.py`.

**Comment by AstroStucky** [comment]
Here's the full sequence of events I see when I tick `camera_left_trigger_failure`, call `rosrun ow_lander camera_capture.py`, then untick the fault, then recall the action. 
```
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] Fault in SYSTEM: CameraGoalError
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] PLEXIL: System fault present.
[ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] PLEXIL: System fault present.
[ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] PLEXIL: System fault present.
[ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
[ WARN:/ow_exec_node] PLEXIL: System fault present.
[ WARN:/ow_exec_node] PLEXIL: Camera goal error present.
[ WARN:/ow_exec_node] Fault in SYSTEM: CameraExecutionError
[ WARN:/ow_exec_node] Resolved fault in SYSTEM: CameraExecutionError
[ WARN:/ow_exec_node] Resolved fault in SYSTEM: CameraGoalError
[ WARN:/ow_exec_node] Fault in CAMERA: NoImageError
[ WARN:/ow_exec_node] Resolved fault in CAMERA: NoImageError
[ INFO:/ow_exec_node] PLEXIL: Polling for faults...
```

**Comment by kmdalal** [comment]
> Same result. How are you triggering the camera? I'm using `rosrun ow_lander camera_capture.py`.

Thanks for the transcript.  I've only been using RQT, which just publishes the trigger message.  Offhand I don't know why the result would differ.   Could you please try this way?  I'll try the action script in a while -- am immersed in another PR at the moment.

**Comment by AstroStucky** [comment]
I just did try by ticking the trigger in RQT, and interestingly I got your result, so I suspect you'll see my result by using the action. It's not clear why it would work this way, but I suspect it's an ow_simulator problem, and is out of scope for this PR.

**Comment by kmdalal** [comment]
> I just did try by ticking the trigger in RQT, and interestingly I got your result, so I suspect you'll see my result by using the action. It's not clear why it would work this way, but I suspect it's an ow_simulator problem, and is out of scope for this PR.

Interesting.  If it's easy to fix, would be good to include it.  It's important because all camera captures from autonomy will be done using the action.  If it can't be fixed today, a hotfix later would be fine.

**Comment by AstroStucky** [comment]
> Interesting. If it's easy to fix, would be good to include it. It's important because all camera captures from autonomy will be done using the action. If it can't be fixed today, a hotfix later would be fine.

I think this needs to be a hotfix unless we want to push back deadlines again. I would not even know where to start as I do not know how that RQT camera trigger works. 

It has a ticket now https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1243

**Pull request merged**
