### PR TITLE
templatize the done_cb as an arg for the runAction method

### PR DESCRIPTION
**Pull request by Samahu**
## Linked Issues:
| EPIC ⚡|  [OCEANWATER-586 / OceanWATERS Action clients](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-586) |
| :----------- | :----------- |
| Jira Ticket 🎟️  | [OCEANWATER-670 / refactor runAction to allow passing the done_cb as an arg](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-670) |
| Github :octocat:  | #32 |

## Summary of Changes
* Templatize the done_cb function for the runAction
```C++
template<int OpIndex, typename T>
using t_action_done_cb = void (*)(const actionlib::SimpleClientGoalState& state, const T& result_ignored);

class class OwInterface
{
  /* ... */
  template <int OpIndex, class ActionClient, class Goal,
    class ResultPtr, class FeedbackPtr>
    void runAction (const std::string& opname,
                    std::unique_ptr<ActionClient>&,
                    const Goal&, int id,
                    /*NEW*/t_action_done_cb<OpIndex, ResultPtr> done_cb = action_done_cb<OpIndex, ResultPtr>/*NEW*/);
  /* ... */
};
```

## Test
* Build succeeds with no errors

### CODE REVIEW

**Comment by kmdalal** [comment]
I merged in some small fixes from the target branch, and made the minor change we discussed.  Code looks great.  For some reason, ReferenceMission1 is failing on GuardedMove.   Could you please retry?  I'm using sim branch OW-534 of course.

**Comment by Samahu** [comment]
> I merged in some small fixes from the target branch, and made the minor change we discussed. Code looks great. For some reason, ReferenceMission1 is failing on GuardedMove. Could you please retry? I'm using sim branch OW-534 of course.

I am getting an error message during **ow_autonomy** startup which says: `GuardedMove action server did not connect!`.

I did verify that this error already exists on the branch `OCEANWATER-586-action-clients` so this is technically beyond the scope of this PR, but i will have a quick look into it to see if I can fix it.

**Comment by kmdalal** [comment]
Okay, my experience is consistent.  It started after some work on the 586 branch that offhand, I'm not sure how would have introduced it.  I can't look at it until later this afternoon.

**Comment by Samahu** [comment]
> Okay, my experience is consistent. It started after some work on the 586 branch that offhand, I'm not sure how would have introduced it. I can't look at it until later this afternoon.

The issue took place when you change the value of **Op_GuardedMove** from  "Guarded_move" to "GuardedMove" (when I asked why this is not consistent with the rest of the named. However, in order for this renaming to work you would need to rename the name name of the corresponding action server in `guarded_move_action_server.py`

**Comment by Samahu** [comment]
There is probably a reason why Anjan named the GuardedMove Action Server as "Guarded_move". Undoing the renaming should fix the problem.

**Comment by kmdalal** [comment]
Ah, I'd completely forgotten the real reason for "Guarded_move" and I should have commented that.  I'll reset it for now, and check with Anjan on whether this rename is trivial on the sim side; if so we should do it.  Thanks for debugging.

**Review by kmdalal — APPROVED** [review]
I renamed back to Guarded_move and all worked fine.

**Pull request merged**
