### PR TITLE
OCEANWATER-649 EuropaMission plan revamp

### PR DESCRIPTION
**Pull request by kmdalal**
In addition to the changes described in the Jira, there is a small plan refactoring and addition of comments.

To test, start any simulator world, and run the EuropaMission plan:

roslaunch ow_autonomy autonomy_node.launch plan:=EuropaMission.plx

### CODE REVIEW

**Review by Samahu — APPROVED** [review]
I have tested this and it executed successfully. I cannot comment on the actual plan since i don't the exact steps to be carried out and how it is differs from the `ReferenceMission1.plx`

I have noticed that the battery remaining useful life is not updating correctly but since you already have a ticket for that then we can leave it outside of the PR.

One last thing, I have noticed that you have added a flag called **DidCrash** that you check its value throughout PLEXIL scripts. However, I couldn't see where this flag have its value changed neither in C++ nor in PLEXIL, can you elaborate please?

**Comment by kmdalal** [comment]
> I have tested this and it executed successfully. I cannot comment on the actual plan since i don't know the exact steps that this plan is supposed to carry out and how it is differs from the `ReferenceMission1.plx`

It should carry out exactly the same steps sequence as ReferenceMission1, but with additional, stubbed steps embedded, such as various imaging and downlinks.
> 
> I have noticed that the battery remaining useful life is not updating correctly but since you already have a ticket for that then we can leave it outside of the PR.

Correct, this works in a parallel branch.

> One last thing, I have noticed that you have added a flag called **DidCrash** that you check its value throughout PLEXIL scripts. However, I couldn't see where this flag have its value changed neither in C++ nor in PLEXIL, can you elaborate please?

PLEXIL commands and Lookups are handled by the Adapters listed in plans/ow-config.xml.  Each adapter registers itself to handle specific commands and lookups, and I believe the adapters are tried in the order listed.  The final adapter "ow_adapter", which is implemented by plexil-adapter/OwAdapter.cpp is the default handler for anything that passes through, i.e. the domain-specific lookups and commands.   The DidCrash lookup is handled by the Checkpoint adapter, which is part of PLEXIL; is is not OW-specfic.   I will add a brief explanation of adapters to the Autonomy chapter of our user guide.

**Comment by lanseafood** [comment]
@kmdalal  there seems to be some merge conflicts to resolve

**Comment by lanseafood** [comment]
Get these errors during the build:
Warnings   << ow_autonomy:make /home/mlma/oceanwaters_ws/logs/ow_autonomy/build.make.036.log
Error: file '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/InterogateSurface.plp' does not exist or is not readable
cc: error: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/InterogateSurface.plp: No such file or directory
cc: warning: ‘-x c’ after last input file has no effect
cc: fatal error: no input files
compilation terminated.
Error: Preprocessing of '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/InterogateSurface.plp' failed.
Unable to open input file /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/InterogateSurface.ple: java.io.FileNotFoundException: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/InterogateSurface.ple (No such file or directory)
Error: Standard Plexil compilation of  failed.
Error: file '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorBattery.plp' does not exist or is not readable
cc: error: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorBattery.plp: No such file or directory
cc: warning: ‘-x c’ after last input file has no effect
cc: fatal error: no input files
compilation terminated.
Error: Preprocessing of '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorBattery.plp' failed.
Unable to open input file /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorBattery.ple: java.io.FileNotFoundException: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorBattery.ple (No such file or directory)
Error: Standard Plexil compilation of  failed.
Error: file '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesComplete.plp' does not exist or is not readable
cc: error: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesComplete.plp: No such file or directory
cc: warning: ‘-x c’ after last input file has no effect
cc: fatal error: no input files
compilation terminated.
Error: Preprocessing of '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesComplete.plp' failed.
Unable to open input file /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesComplete.ple: java.io.FileNotFoundException: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesComplete.ple (No such file or directory)
Error: Standard Plexil compilation of  failed.
Error: file '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesIntegrity.plp' does not exist or is not readable
cc: error: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesIntegrity.plp: No such file or directory
cc: warning: ‘-x c’ after last input file has no effect
cc: fatal error: no input files
compilation terminated.
Error: Preprocessing of '/home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesIntegrity.plp' failed.
Unable to open input file /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesIntegrity.ple: java.io.FileNotFoundException: /home/mlma/oceanwaters_ws/src/ow_autonomy/src/plans/MonitorSamplesIntegrity.ple (No such file or directory)
Error: Standard Plexil compilation of  failed.
cd /home/mlma/oceanwaters_ws/build/ow_autonomy; catkin build --get-env ow_autonomy | catkin env -si  /usr/bin/make --jobserver-fds=9,10 -j; cd -

**Comment by lanseafood** [comment]
@kmdalal 

when running, get this immediate error before it continues :
[ERROR] [1618950521.777397748, 1916524860.397500038]: Client [/autonomy_node] wants topic /power_system_node/remaining_useful_life to have datatype/md5sum [std_msgs/Float64/fdb28210bfa9d7c91146260178d9a584], but our version has [std_msgs/Int16/8524586e34fbd7cb1c08c5f5f1ca0e57]. Dropping connection.

other than that seems to run alright. Seems to run for a pretty long time, I'm not sure what to expect out of running this plan, but it ends in stow arm afaik.

**Review by lanseafood — APPROVED** [review]

**Comment by kmdalal** [comment]
> @kmdalal
> 
> when running, get this immediate error before it continues :
> [ERROR] [1618950521.777397748, 1916524860.397500038]: Client [/autonomy_node] wants topic /power_system_node/remaining_useful_life to have datatype/md5sum [std_msgs/Float64/fdb28210bfa9d7c91146260178d9a584], but our version has [std_msgs/Int16/8524586e34fbd7cb1c08c5f5f1ca0e57]. Dropping connection.
> 
> other than that seems to run alright. Seems to run for a pretty long time, I'm not sure what to expect out of running this plan, but it ends in stow arm afaik.

I don't get that error.  It suggests you have a stale copy of the branch.  I updated it during Dev Day this morning and indicated that in the chat while you were away.  

The plan does indeed run a long time.  End is indicated with "PLEXIL: Europa Mission, Sol 0 finished."  I'll mention this in the release test.

**Pull request merged**
