### PR TITLE
OWLAT Sequence 4 Fix

### PR DESCRIPTION
**Pull request by MilanAdd**
Originally, when I executed Test Sequence 4 at the point where it was executing the retracting ARM_PLACE_TOOL command, something unusual was happening. Instead of the arm retracting above the surface, it went deeper into the terrain. To fix this, I changed the distance value in the second ARM_PLACE_TOOL from this:
```
LibraryCall OwlatArmPlaceTool(Frame=frame, Relative=relative, Position=position,
                                Normal=normal, Distance=distance, Overdrive=overdrive, Retracting=true,
                                ForceThreshold=force_threshold, TorqueThreshold=torque_threshold);
```

to its additive inverse:
```
LibraryCall OwlatArmPlaceTool(Frame=frame, Relative=relative, Position=position,
                                Normal=normal, Distance=(-distance), Overdrive=overdrive, Retracting=true,
                                ForceThreshold=force_threshold, TorqueThreshold=torque_threshold);
```

and now Test Sequence 4 is executing properly.

I also added an ARM_UNSTOW command as the last command of the PLEXIL plan instead of the second ARM_PLACE_TOOL command.

### CODE REVIEW

**Comment by MilanAdd** [comment]
That is weird. I re-ran the sequence and everything seemed to be good on my end.

**Comment by MilanAdd** [comment]
Can I close this pull request and start a new one from a different branch? The 'OWLAT-Sequence-4-Fix' branch is acting a bit funky for me on git.

**Comment by kmdalal** [comment]
> Can I close this pull request and start a new one from a different branch? The 'OWLAT-Sequence-4-Fix' branch is acting a bit funky for me on git.

The server version of this branch builds fine for me.  Does 'git status' tell you anything?  You could also delete your local copy of the branch and re-fetch it from the server.  It's uncommon to scrap a branch and start over, but if you're stumped that would be fine.

**Comment by kmdalal** [comment]
I've tested every arm operation repeatedly -- a single or arbitrary test is not sufficient for such a feature.  While in most cases I see the behavior I'd expect, there is quite a bit of unspecified behavior, including some surprising ones such as digs happening with the side of the scoop when moving during faults.  

The user documentation should be part of this work, in particular because the expected behavior isn't completely intuitive.  For example, we could document (if this is the intended behavior) that if continue_arm_in_fault is false, an injected fault will always fail the operation.  But when continue_arm_in_fault is true, an injected fault will not fail the operation if it is cleared before the operation finishes; otherwise the operation fails.

**Comment by kmdalal** [comment]
Sorry, the last comment I had left (deleted) was for another PR!

I think the last thing remaining here is putting in the ArmUnstow workaround that Ashish suggested.

**Comment by MilanAdd** [comment]
Wait, this may be a silly question, but do you think that Ashish meant to replace the second ARM_PLACE_TOOL with the ARM_UNSTOW command or did he mean to add ARM_UNSTOW after each ARM_PLACE_TOOL command? I will ask him this anyways for confirmation.

**Comment by MilanAdd** [comment]
Yep, he said to replace the ARM_PLACE_TOOL command with the ARM_UNSTOW command, which was what I thought he meant.

As mentioned in the email that I sent, I know that this change works because I tested this out around a week an half or two ago, so for now, Test Sequence 4 should be fine.

**Comment by MilanAdd** [comment]
> Yep, he said to replace the ARM_PLACE_TOOL command with the ARM_UNSTOW command, which was what I thought he meant.
> 
> As mentioned in the email that I sent, I know that this change works because I tested this out around a week an half or two ago, so for now, Test Sequence 4 should be fine.

By the way, I already pushed a commit a couple of hours ago that did this, so you can test it out now.

**Review by kmdalal — APPROVED** [review]
I retested #4 and all the other sequences.  Looks good!

**Pull request merged**
