### PR TITLE
Minor proposal (line 70)

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by kmdalal** [comment]
Thanks for catching the typo!  This has been fixed, along with other changes, on the melodic-devel branch.  We in the process of making a new release and hope to have the master branch updated soon.

**Comment by kmdalal** [comment]
Thanks again for the feedback, @kant.  This has been incorporated along with a more extensive edit.

**Comment by kant** [comment]
A pleasure, Sir

**Comment by kant** [comment]
> Thanks again for the feedback, @kant. This has been incorporated along with a more extensive edit.

A pleasure, Sir

**Pull request closed without merging**
