### PR TITLE
Improve ReferenceMission1 sample target search.

### PR DESCRIPTION
**Pull request by kmdalal**
### Summary
- This work supports the same branch's PRs in ow_simulator and ow_europa and should be merged when they are.  However, the improvements are independent of those PRs and work in noetic-devel, so this could be merged by itself.   There are also a few extra improvements.
 - An actual search for a suitable sample target is performed, instead of using a pre-chosen point.
 - Because the current image search parameters fail to find a suitable target, a default one is used.  Hence, ReferenceMission1 always does a sampling attempt.
 - Unrelated but minor: reduce bite depth to 0.3 in RemoveTailings to lower the risks of excessive force on the scoop that resulted from recent work.
 - Misc/minor: Python script always returns 3 values explicitly.  Many lines were shortened.  (And many are still quite long).  Comments were cleaned up.

### Test

Run ReferenceMission1 twice, using two different branches of ow_simulator and ow_europa: the feature branch and noetic-devel.

In both branches, it will do a longer scan of the workspace, which includes pans and tilts.  Using noetic-devel, a target location is found quickly.  Using the feature branch, a target location is not found and these warnings appear:
```
 [ WARN]: PLEXIL: IdentifySampleTarget: failed to find a suitable sample target.
[ WARN]: PLEXIL: Sampling location could not be found visually. Using default dig location.
```
In both branches, the plan completes the sampling operation as it did before.

### CODE REVIEW

**Comment by kmdalal** [comment]
@AstroStucky , the only operational Python code change was a single return statement.  The rest is formatting.  Feel free to further improve it.

**Comment by AstroStucky** [comment]
Just an aside about ReferenceMission1 and the other plans. I see now why the scoop tends to scoop too deep. The scoop bite depth of 5cm is hard-coded into `RemoveTailings.plp`. This value would've worked fine pre-Release 12, but now that we have a dig force model we really should target bite depths of about 2-3cm to avoid weird scoop behavior. I also think it would make sense to expose the bite depth and passes parameters as an In arguments like they are for `DigTrench.plp`.

**Review by AstroStucky — COMMENTED** [review]
Tests pass, and code looks good to me. 

Are you still planning on modifying ReferenceMission2 and EuropaMission in this PR too?

**Comment by kmdalal** [comment]
> Just an aside about ReferenceMission1 and the other plans. I see now why the scoop tends to scoop too deep. The scoop bite depth of 5cm is hard-coded into `RemoveTailings.plp`. This value would've worked fine pre-Release 12, but now that we have a dig force model we really should target bite depths of about 2-3cm to avoid weird scoop behavior. I also think it would make sense to expose the bite depth and passes parameters as an In arguments like they are for `DigTrench.plp`.

Good catch.  Changing this seems important.  Do you think it's small enough to include in this PR, even though it's unrelated?

**Comment by kmdalal** [comment]
> Tests pass, and code looks good to me.

Good to hear.

> Are you still planning on modifying ReferenceMission2 and EuropaMission in this PR too?

Yes, just hadn't gotten to it yet.  I'll ping you when it's pushed.

**Comment by AstroStucky** [comment]
> Good catch. Changing this seems important. Do you think it's small enough to include in this PR, even though it's unrelated?

Up to you. It's small enough to only require a handful of lines of code, but it's also unrelated. I'm happy to test all 3 missions as part of the change if you want to just put it in this PR for expediency.

**Comment by kmdalal** [comment]
@AstroStucky I have converted EuropaMission and ReferenceMission2 and tested both.  I reduced the bite depth to 0.03 and the scooping seems smoother.  There are other plans that use a 0.05 bite depth but these can be converted later.

**Comment by AstroStucky** [comment]
The dig in ReferenceMission1 looks much better! FYI the actual sample collection now collects way more sample, because the final depth to which tailings have been removed from is now less. I don't know if that's a problem or not, just wanted to point it out so you're aware.

**Comment by AstroStucky** [comment]
Plans all worked fine, but I noticed they all had this warning at the end. 
```
[ WARN:/ow_exec_node] Unsupported Plexil Lookup ExitPlan, called with 1 arguments
```

**Comment by AstroStucky** [comment]
In only EuropaMission I encountered the following two warnings from identify_sample_location. 
```
[ INFO:/ow_exec_node] IdentifySampleLocation () started...
[WARN:/identify_sample_location] Goal is larger than total images recorded, only 1 images will be processed.
[INFO:/identify_sample_location] identify_sample_location.py: location rejected.
[ INFO:/ow_exec_node] Pan (1.309) started...
[ INFO:/ow_exec_node] Pan finished in state SUCCEEDED
[ INFO:/ow_exec_node] CameraCapture () started...
[ INFO:/ow_exec_node] CameraCapture finished in state SUCCEEDED
[WARN:/identify_sample_location] Goal is larger than total images recorded, only 2 images will be processed.
[ INFO:/ow_exec_node] IdentifySampleLocation () started...
[INFO:/identify_sample_location] identify_sample_location.py: location rejected.
```

**Comment by AstroStucky** [comment]
One more aside about RemoveTailings. I think the discard location should be made a little higher. Because MoveIt will typically pick a final configuration where the hand joint is lower than the scoop dumping this low will sometimes result in trajectory planning failure or the hand or scoop colliding with the terrain when the trajectory is executed.

**Review by AstroStucky — APPROVED** [review]

**Comment by kmdalal** [comment]
> Plans all worked fine, but I noticed they all had this warning at the end.
> 
> ```
> [ WARN:/ow_exec_node] Unsupported Plexil Lookup ExitPlan, called with 1 arguments
> ```

Known issue that is a minor Plexil executive bug and is on our Caveats page.

**Comment by kmdalal** [comment]
> [WARN:/identify_sample_location] Goal is larger than total images recorded, only 1 images will be processed.

I've never seen this, and don't know the code well enough to understand its significance.  Suggest investigating later if it becomes an issue.

**Comment by kmdalal** [comment]
> One more aside about RemoveTailings. I think the discard location should be made a little higher. Because MoveIt will typically pick a final configuration where the hand joint is lower than the scoop dumping this low will sometimes result in trajectory planning failure or the hand or scoop colliding with the terrain when the trajectory is executed.

Noting this for future work.

**Pull request merged**
