### PR TITLE
Oceanwater 938 - OWLAT Test Sequence 6 errors

### PR DESCRIPTION
**Pull request by MilanAdd**
Originally, there was a error when executing OwlatTestSequence6.plp (seen below):

```
145.583043874 DIAGNOSTIC [TASK]: dropoff entering Hover
148.930425418 DIAGNOSTIC [TASK]: dropoff entering Dropoff
206.100120507 ERROR [DARTS]: Failed to step DARTS clock!
206.100144038 ERROR: FaultProtection: Fault! ARM_EXECUTION_ERROR
206.100169878 ERROR: FaultProtection: Fault! DARTS_INTERNAL_ERROR
206.101538052 ERROR [DARTS]: failed to send CmdPrescribeJointAngles
206.150866703 STDERR [LOG]: [ERROR] [1655744675.200273771]: Service call failed: service [/CmdStep] responded with an error: Problem with integration at t=152.15,  cvode status=-3 (Error in DIntegratorCvode::lastStatus(): Error test failures occured too many times (ERR_FAILURE))
206.150923564 STDERR [LOG]: 
206.150929324 ERROR: FaultProtection: Fault! ARM_GOAL_ERROR
206.150938234 STDERR [LOG]: [ERROR] [1655744675.202477190]: Service call failed: service [/CmdPrescribeJointAngles] responded with an error: Simulation::lockObject can only be called in the INITIALIZING or READY simulation phase, and not in the current SimulationPhase_WITHIN_INTEGRATION_STEP phase.
206.150964944 STDERR [LOG]: 
206.151063776 ERROR [ROS]: Command TASK_DROPOFF 140145521112672 Failure could not complete Dropoff Arm violated safety limits
```

I reviewed and verified each test sequence in OWLAT in relation to the latest Noetic test guide and what I've found out was that in the Test Sequence 6 PLEXIL plan, there was a TASK_DROPOFF command that wasn't present in Test Sequence 6 section of the user guide. What I did was just removed that command and now that test sequence seems to be working properly.

### CODE REVIEW

**Review by kmdalal — CHANGES_REQUESTED** [review]
Looks good!  I'd like to add one more related step to this work: remove the support for TASK_DROPOFF from Plexil altogether, since JPL has discontinued this command.  This will be a good simple introduction to the C++ side of PLEXIL.  The starting place is OwlatAdapter.cpp.

**Comment by MilanAdd** [comment]
Is all the support for TASK_DROPOFF found in the plexil-adapter and owlat_plans folders or are there other folders where TASK_DROPOFF support is present?

**Comment by kmdalal** [comment]
> Is all the support for TASK_DROPOFF found in the plexil-adapter and owlat_plans folders or are there other folders where TASK_DROPOFF support is present? I just want to double check on that.

Those should be the only ones!

**Comment by MilanAdd** [comment]
Alright, I removed all the TASK_DROPOFF support from PLEXIL.

**Review by kmdalal — APPROVED** [review]
Well done!

**Pull request merged**
