### PR TITLE
Oceanwater 622 faults var rename

### PR DESCRIPTION
**Pull request by lanseafood**
Sister PR for https://github.com/nasa/ow_simulator/pull/111

### CODE REVIEW

**Review by Samahu — APPROVED** [review]
Approved but same [discussion](https://github.com/nasa/ow_simulator/pull/98#issuecomment-820805846) applies.

**Review by Samahu — COMMENTED** [review]
Note that this branch merges directly into **melodic-devel** branch meanwhile the PR https://github.com/nasa/ow_simulator/pull/111 merges into **OCEANWATER-581_power_faults_impact_ros_topics**. i.e. this needs to be merged at the same time as **OCEANWATER-581_power_faults_impact_ros_topics** branch is merged into **melodic-devel**

**Comment by kmdalal** [comment]
@lanseafood Is this PR and branch still relevant?

**Comment by lanseafood** [comment]
> @lanseafood Is this PR and branch still relevant?

yes, as stated in the description, this PR allows for the naming changes to be consistent for changes in ow_simulator

**Comment by kmdalal** [comment]
Got it.  Sorry, I missed the description.   Essentially this is waiting on OW-581 to get merged.

**Pull request merged**
